version: 2

sources:
  - name: source
    database: PRACTICE_DB
    schema: MYPRAC
    tables:
      - name: customers
      - name: products
      - name: orders
      - name: order_items
      - name: payments
